# Generated by Django 3.2.4 on 2021-06-23 14:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('public', models.BooleanField()),
                ('url_video', models.CharField(default='NUll', max_length=400, null=True, verbose_name='Ссылка на видео')),
                ('text', models.CharField(max_length=4000, verbose_name='Инструкция')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('meal_type', models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин'), ('Напиток', 'Напиток'), ('Десерт', 'Десерт')], default='завтрак', max_length=50, verbose_name='Название трапезы')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Typing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.IntegerField(verbose_name='Сложность приговления блюда')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления в секундах')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
            ],
            options={
                'verbose_name': 'типизация',
                'verbose_name_plural': 'типизации',
                'ordering': ['-recipe_id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Пользовательский рейтинг блюда')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
                'ordering': ['-recipe_id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('value', models.IntegerField(verbose_name='Вес ингредиента в граммах')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
            ],
            options={
                'verbose_name': 'ингридиент',
                'verbose_name_plural': 'ингридиенты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Любимые блюдо',
                'verbose_name_plural': 'любимые блюда',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата время')),
                ('text', models.CharField(max_length=200, verbose_name='Коментарий пользователя')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['-data_time'],
            },
        ),
    ]
