# Generated by Django 3.2.4 on 2021-06-23 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Название трапезы')),
            ],
            options={
                'verbose_name': 'трапеза',
                'verbose_name_plural': 'трапезы',
                'ordering': ['-type'],
            },
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Имя блюда')),
                ('public', models.BooleanField()),
                ('url_video', models.CharField(default='NUll', max_length=400, null=True, verbose_name='Ссылка на ютую видео')),
                ('text', models.CharField(max_length=4000, verbose_name='Инструкция')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='typing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.IntegerField(verbose_name='Сложность приговления по 5 бальной шкале')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления в секундах')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.meal')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
            ],
            options={
                'verbose_name': 'типизация',
                'verbose_name_plural': 'типизации',
                'ordering': ['-recipe_id'],
            },
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(verbose_name='Рейтинг блюда поставленное пользователем по 5 бальной шкале')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
                'ordering': ['-recipe_id'],
            },
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название ингредиента')),
                ('value', models.IntegerField(verbose_name='Вес ингредиента в граммах')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
            ],
            options={
                'verbose_name': 'ингридиент',
                'verbose_name_plural': 'ингридиенты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='favorite_dishes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Любимые блюдо',
                'verbose_name_plural': 'любимые блюда',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datatime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата время')),
                ('text', models.CharField(max_length=200, verbose_name='Сам коментарий')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
