# Generated by Django 3.2.4 on 2021-06-24 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ingredients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='complexity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Сложность приговления блюда'),
        ),
    ]
