# Generated by Django 3.2.4 on 2021-06-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_typing_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.recipe', verbose_name='ID блюда'),
        ),
    ]
