# Generated by Django 3.2.4 on 2021-06-24 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_typing_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Пользовательский рейтинг блюда'),
        ),
        migrations.AlterField(
            model_name='typing',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='ID блюда'),
        ),
    ]
